from unittest.mock import patch, MagicMock

from app.graph.nodes.triage import triage_node
from app.graph.nodes.action import action_node
from app.graph.nodes.comms import comms_node

# ==========================================
# 1. TEST THE TRIAGE NODE
# ==========================================
@patch("app.graph.nodes.triage.get_llm")
def test_triage_node(mock_get_llm):
    """Ensure the triage node correctly parses drift and outputs severity/action."""
    
    mock_llm_chain = MagicMock()
    
    # FIX 1: Return a standard dictionary instead of a mock object
    mock_response = {
        "severity": "critical",
        "action": "rollback", 
        "recommended_action": "rollback", # Added both just in case your schema uses 'action'
        "reasoning": "Test reasoning."
    }
    
    mock_llm_chain.invoke.return_value = mock_response
    mock_get_llm.return_value.with_structured_output.return_value = mock_llm_chain

    initial_state = {
        "drift_event": {"euribor3m": "critical"},
        "active_version": "v1"
    }

    result_state = triage_node(initial_state)

    assert result_state["severity"] == "critical"
    assert result_state["recommended_action"] == "rollback"
    assert "Test reasoning" in result_state["reasoning"]

# ==========================================
# 2. TEST THE ACTION NODE (HUMAN DENIED)
# ==========================================
def test_action_node_denied():
    """Ensure the action node safely handles a human denial without calling the LLM."""
    
    initial_state = {
        "human_approved": False,
        "recommended_action": "rollback"
    }
    
    result_state = action_node(initial_state)
    
    assert result_state["job_id"] == "DENIED-BY-HUMAN"
    assert result_state["recommended_action"] == "denied"

# ==========================================
# 3. TEST THE COMMS NODE
# ==========================================
@patch("app.graph.nodes.comms.get_llm")
def test_comms_node(mock_get_llm):
    """Ensure the comms node formats a final summary message."""
    
    mock_llm = MagicMock()
    mock_llm.invoke.return_value.content = "Fake final summary generated by LLM."
    mock_get_llm.return_value = mock_llm

    initial_state = {
        "severity": "critical",
        "recommended_action": "denied",
        "job_id": "DENIED-BY-HUMAN",
        "drift_event": {},
        "reasoning": "Test reasoning",
        "active_version": "v1"
    }
    
    # FIX 2: Create a fake config to satisfy the comms_node signature
    dummy_config = {"configurable": {"thread_id": "test-thread-1234"}}

    # Pass the dummy config alongside the state
    result_state = comms_node(initial_state, config=dummy_config)

    assert result_state["summary"] == "Fake final summary generated by LLM."